version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post_checkout:
      - >
        gitlfs_ver="3.2.0"; 
        wget -qO- https://github.com/git-lfs/git-lfs/releases/download/v${gitlfs_ver}/git-lfs-linux-amd64-v${gitlfs_ver}.tar.gz 
        | tar -xOz git-lfs-${gitlfs_ver}/git-lfs > git-lfs
      - chmod u+x git-lfs
      - git config filter.lfs.process "`pwd`/git-lfs filter-process"
      - git config filter.lfs.smudge  "`pwd`/git-lfs smudge -- %f"
      - git config filter.lfs.clean "`pwd`/git-lfs clean -- %f"
      - ./git-lfs install
      - ./git-lfs fetch
      - ./git-lfs checkout

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
