[tool.poetry]
name = "sethfischer-osr"
version = "0.1.0"
description = "Alternative body construstion for the NASA JPL Open Source Rover."
authors = [
    "Seth Fischer <seth@fischer.nz>",
]
readme = "README.rst"
license = "MIT"
homepage = "https://github.com/sethfischer/osr"
repository = "https://github.com/sethfischer/osr.git"
documentation = "https://sethfischer-osr.readthedocs.io/"
keywords = [
    "jpl",
    "mars",
    "robot",
    "robotics",
    "rover",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Private :: Do not Upload",  # Prevent uploading to PyPi
    "Topic :: Education",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sethfischer/osr/issues"

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"
sphinx-lfs-content = "^1.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^22.1.0"
isort = "^5.10.1"
cffconvert = "^2.0.0"
doc8 = "^0.10.1"
rstcheck = "^3.3.1"
flake8-docstrings = "^1.6.0"

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
